sudo: false

language: go

go:
  - 1.6
  - tip

matrix:
  allow_failures:
    - go: tip

branches:
  only:
    - master
    - travis-testing

install:
  - go install vault

script:
  - make test testrace
